// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyAAMUmYcLWtoGmezikEts9xi8tCy-Ph5PE', // Assuming same API Key as iOS for now
    appId: '1:170112107448:web:ce6415494dff9770513812', // From log
    messagingSenderId: '170112107448',
    projectId: 'earsmile-71887',
    authDomain: 'earsmile-71887.firebaseapp.com',
    storageBucket: 'earsmile-71887.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyAAMUmYcLWtoGmezikEts9xi8tCy-Ph5PE', // Assuming same API Key as iOS for now
    appId: '1:170112107448:android:6dc6650426b3c945513812', // From log
    messagingSenderId: '170112107448',
    projectId: 'earsmile-71887',
    storageBucket: 'earsmile-71887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAMUmYcLWtoGmezikEts9xi8tCy-Ph5PE',
    appId: '1:170112107448:ios:ebb145578aba49352d054d',
    messagingSenderId: '170112107448',
    projectId: 'earsmile-71887',
    storageBucket: 'earsmile-71887.firebasestorage.app',
    iosBundleId: 'com.example.earsmile',
  );

}