// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/app_settings.dart';
import 'models/conversation.dart';
import 'models/message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7850056176677781307),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(3, 4967370486353035027),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5495975526664060416),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1169068320434970109),
        name: 'fontSize',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4967370486353035027),
        name: 'isHighContrast',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6741828154858768197),
    name: 'Conversation',
    lastPropertyId: const obx_int.IdUid(7, 3163312255999005973),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1594886700761233819),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6462489653068323967),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2099036530929294395),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8531389249446460809),
        name: 'startedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(2, 2518682059330772208),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4459786182007179107),
        name: 'endedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2529607417815776252),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6931173290829098972),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3163312255999005973),
        name: 'isSyncedToCloud',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8310160554013422074),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(7, 5471605041641322173),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5725509081333054952),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8161298042236708059),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 6242334623807565067),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 355724175885039124),
        name: 'conversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3968840274249412),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7891273678579613600),
        name: 'timestamp',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(5, 6444550269682103634),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5171578378597867025),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6217982716190542774),
        name: 'confidence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5471605041641322173),
        name: 'isFinal',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8310160554013422074),
    lastIndexId: const obx_int.IdUid(5, 6444550269682103634),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[0],
      toOneRelations: (AppSettings object) => [],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.fontSize);
        fbb.addBool(2, object.isHighContrast);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fontSizeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final isHighContrastParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object = AppSettings(
          id: idParam,
          fontSize: fontSizeParam,
          isHighContrast: isHighContrastParam,
        );

        return object;
      },
    ),
    Conversation: obx_int.EntityDefinition<Conversation>(
      model: _entities[1],
      toOneRelations: (Conversation object) => [],
      toManyRelations: (Conversation object) => {},
      getId: (Conversation object) => object.id,
      setId: (Conversation object, int id) {
        object.id = id;
      },
      objectToFB: (Conversation object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.startedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.endedAt?.millisecondsSinceEpoch);
        fbb.addOffset(4, titleOffset);
        fbb.addBool(5, object.isFavorite);
        fbb.addBool(6, object.isSyncedToCloud);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final startedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final endedAtParam = endedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endedAtValue);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final isSyncedToCloudParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = Conversation(
          id: idParam,
          uuid: uuidParam,
          startedAt: startedAtParam,
          endedAt: endedAtParam,
          title: titleParam,
          isFavorite: isFavoriteParam,
          isSyncedToCloud: isSyncedToCloudParam,
        );

        return object;
      },
    ),
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[2],
      toOneRelations: (Message object) => [],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.id,
      setId: (Message object, int id) {
        object.id = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, conversationIdOffset);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, textOffset);
        fbb.addFloat64(5, object.confidence);
        fbb.addBool(6, object.isFinal);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final conversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final confidenceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final isFinalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = Message(
          id: idParam,
          uuid: uuidParam,
          conversationId: conversationIdParam,
          timestamp: timestampParam,
          text: textParam,
          confidence: confidenceParam,
          isFinal: isFinalParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[0].properties[0],
  );

  /// See [AppSettings.fontSize].
  static final fontSize = obx.QueryDoubleProperty<AppSettings>(
    _entities[0].properties[1],
  );

  /// See [AppSettings.isHighContrast].
  static final isHighContrast = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[2],
  );
}

/// [Conversation] entity fields to define ObjectBox queries.
class Conversation_ {
  /// See [Conversation.id].
  static final id = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[0],
  );

  /// See [Conversation.uuid].
  static final uuid = obx.QueryStringProperty<Conversation>(
    _entities[1].properties[1],
  );

  /// See [Conversation.startedAt].
  static final startedAt = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[2],
  );

  /// See [Conversation.endedAt].
  static final endedAt = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[3],
  );

  /// See [Conversation.title].
  static final title = obx.QueryStringProperty<Conversation>(
    _entities[1].properties[4],
  );

  /// See [Conversation.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Conversation>(
    _entities[1].properties[5],
  );

  /// See [Conversation.isSyncedToCloud].
  static final isSyncedToCloud = obx.QueryBooleanProperty<Conversation>(
    _entities[1].properties[6],
  );
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[0],
  );

  /// See [Message.uuid].
  static final uuid = obx.QueryStringProperty<Message>(
    _entities[2].properties[1],
  );

  /// See [Message.conversationId].
  static final conversationId = obx.QueryStringProperty<Message>(
    _entities[2].properties[2],
  );

  /// See [Message.timestamp].
  static final timestamp = obx.QueryDateProperty<Message>(
    _entities[2].properties[3],
  );

  /// See [Message.text].
  static final text = obx.QueryStringProperty<Message>(
    _entities[2].properties[4],
  );

  /// See [Message.confidence].
  static final confidence = obx.QueryDoubleProperty<Message>(
    _entities[2].properties[5],
  );

  /// See [Message.isFinal].
  static final isFinal = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[6],
  );
}
